---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.50.11"}]

platforms:
  - name: ubuntu/xenial64

provisioner:
  name: salt_solo
  formula: cockroachdb
  salt_version: 2016.11.2
  state_top:
    base:
      '*':
        - cockroachdb
  pillars:
    top.sls:
      base:
        '*':
          - cockroachdb
  pillars-from-files:
    cockroachdb.sls: pillar.example

suites:
  - name: default
