---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.50.11"}]

platforms:
  - name: ubuntu/xenial64

provisioner:
  name: salt_solo
  formula: cockroachdb
  salt_version: 2016.11.2
  state_top:
    base:
      '*':
        - cockroachdb

suites:
  # use cockroachdb/default.yml as pillar source
  - name: default

  # use pillar.example as pillar source
  - name: pillar
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - cockroachdb
      pillars-from-files:
        cockroachdb.sls: pillar.example

  - name: initdb
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - initdb
        initdb.sls:
          cockroachdb:
            initdb:
              dbuser: oldroach
              database: oldroach_sandbox
              keep_initdb_sql: true
