# Every default value here can be overridden by pillar data with the same key.
cockroachdb:
  download_url: https://binaries.cockroachdb.com/cockroach-latest.linux-amd64.tgz
  home_dir: /opt/cockroachdb
  user: cockroach
  group: cockroach

  initdb:
    dbuser: maxroach
    database: roach_sandbox

    # Set keep_initdb_sql to true to keep the user-provided scripts/initdb.sql script after the first start-up.
    # If this script shouldn't be re-executed on restart, set keep_initdb_sql to false to delete it from the minion
    # filesystem after the first start-up.
    keep_initdb_sql: false

  runtime_options:
    - --insecure=true
    - --store=path=/opt/cockroachdb/data
    - --log-dir=/opt/cockroachdb/log
