cockroachdb:
  download_url: https://binaries.cockroachdb.com/cockroach-latest.linux-amd64.tgz
  home_dir: /opt/cockroachdb
  user: cockroach
  group: cockroach
  initdb:
    dbuser: maxroach
    database: roach_sandbox

    # Set to true to keep the user-provided initdb.sql script.
    # This script is executed on restart, so it must not failed.
    keep_initdb_sql: false
