# Every default value here can be overridden by pillar data with the same key.
cockroachdb:
  download_url: https://binaries.cockroachdb.com/cockroach-latest.linux-amd64.tgz
  home_dir: /opt/cockroachdb

  ps:
    user: cockroach
    group: cockroach
    unit_file_tmpl: salt://cockroachdb/files/cockroachdb.service
    post_start_tmpl: salt://cockroachdb/files/post_start.sh

  runtime_options:
    - --insecure=true
    - --host=localhost
    - --port=26257
    - --store=path=/opt/cockroachdb/data
    - --log-dir=/opt/cockroachdb/log
